open-reaction-database/ord-interface

ord_interface/__init__.py, ord_interface/build_database.py, ord_interface/build_database_test.py, ord_interface/ord_client.py, ord_interface/ord_client_test.py, ord_interface/query.py, ord_interface/query_test.py, ord_interface/search.html, ord_interface/search.py
* Adds `dataset_id` and `doi` to the main postgres table.
* Adds searching by DOI to `ord_client` and the web interface.
=> Search by DOI

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/docker/Dockerfile, ord_interface/query.py, ord_interface/query_test.py, ord_interface/search.html, ord_interface/search.py
=> Report query errors

ord_interface/search.html, ord_interface/search.py
* Don't show the "no matches" warning when the page first loads.
* Fix a bug where the DOI field was not populated from the URL query params.
=> Updates to search interface

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/build_database.py, ord_interface/docker-compose.yml, ord_interface/docker/Dockerfile, ord_interface/query.py, ord_interface/search.html, ord_interface/search.py, run_tests.sh
=> Update search interface to use compact reaction views

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/build_database.py, ord_interface/docker/Dockerfile, ord_interface/ord_client.py, ord_interface/search.html, ord_interface/search.py
* Updates the interface to use ord-schema v0.3.3
* Properly handles CXSMILES
* Adds a LIMIT field to the form
=> Bump ord-schema version

README.md
=> Add link to ORD search website.

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/build_database.py, ord_interface/docker/Dockerfile, ord_interface/query.py, ord_interface/query_test.py, ord_interface/search.html, ord_interface/search.py
* Reaction rows now link to the reaction "landing page" (see https://github.com/open-reaction-database/ord-schema/pull/585).
* Updated `RandomSampleQuery` to use the [tsm_system_rows](https://www.postgresql.org/docs/current/tsm-system-rows.html) extension to retrieve a specific number of randomly selected rows. Hopefully this will improve performance.
=> Updates for search interface

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/docker/Dockerfile, ord_interface/search.html, ord_interface/search.py
* Fix a bug where the reaction landing page would show up as raw HTML
* Fix a bug where USPTO reactions would not be rendered properly
[test.zip](https://github.com/open-reaction-database/ord-interface/files/6287547/test.zip)
=> Updates to the search interface

.github/workflows/cleanup.yml, ord_interface/Dockerfile, ord_interface/build_database_test.py, ord_interface/docker/Dockerfile, ord_interface/ord_client.py, ord_interface/ord_client_test.py, ord_interface/query.py, ord_interface/query_test.py, ord_interface/search.html, ord_interface/search.py
=> Search by dataset ID

README.md, ord_interface/client/search.html, ord_interface/client/search.py
* Adds a "Download" button for search results (returned as a compressed PB `Dataset`)
* Adds the reaction ID to each search result in the table
Resolves #18
=> Download search results

.github/workflows/cleanup.yml, .github/workflows/run_tests.yml, ord_interface/Dockerfile, ord_interface/client/ord_client.py, ord_interface/client/query.py, ord_interface/client/search.py, ord_interface/editor/py/serve.py, pytype.cfg, setup.py
=> Pin google-closure-compiler

app/src/components/HeaderNav.vue, app/src/views/browse/MainBrowse.vue, app/src/views/reaction-view/MainReactionView.vue, app/src/views/reaction-view/ObservationsView.vue, app/src/views/reaction-view/SetupView.vue, app/src/views/reaction-view/WorkupsView.vue, app/vue.config.js
@skearnes A handful of small display updates for the reaction view page. I'll continue to hunt for more and fix as I find them.
=> Vue updates

app/src/components/HeaderNav.vue
=> Fix editor link to avoid 8080 redirect

app/src/components/ModalKetcher.vue, app/src/views/search/SearchOptions.vue
Fixed Ketcher modal CSS so that it appears when user hits the "Draw Molecule" button
Also added some null checks to SearchOptions to prevent crashes of the Search page
Closes #116
=> ORD-116: Fixed Ketcher modal not appearing and add some null checks to SearchOptions

ord_interface/api/queries.py
=> Exact query updates

app/src/views/reaction-view/MainReactionView.vue
=> Fix reactions query in reaction viewer

ord_interface/editor/__init__.py, ord_interface/editor/api/README.md, ord_interface/editor/api/__init__.py, ord_interface/editor/api/conftest.py, ord_interface/editor/api/database.py, ord_interface/editor/api/main.py, ord_interface/editor/api/testdata/empty.pbtxt, ord_interface/editor/api/testdata/full.pbtxt, ord_interface/editor/api/testdata/ord-nielsen-example.pbtxt, ord_interface/editor/api/testing.py, setup.py
This is a trimmed-down version of the existing API.
=> FastAPI editor backend

ord_interface/editor/py/serve.py, ord_interface/editor/py/serve_test.py
The upload page in Contribute only takes uncompressed files.
=> Allow .pb.gz uploads

app/src/views/search/MainSearch.vue, ord_interface/Dockerfile, ord_interface/about.html, ord_interface/api/conftest.py, ord_interface/api/queries.py, ord_interface/api/queries_test.py, ord_interface/api/search.py, ord_interface/editor/py/serve.py, ord_interface/editor/py/serve_test.py, setup.py
This should allow the FastAPI background tasks to run without blocking any other operations.
=> Async database operations

app/src/views/search/MainSearch.vue
=> ord-150 - Fixed issue where the search results would disappear after 2 minutes

README.md
Added some notes to the readme to guide administrators in how to update ord-interface to use new versions of ord-schema.
=> add ord-schema config notes

ord_interface/editor/html/reaction.html
=> Fix broken "delete reaction" button

app/src/components/ReactionCard.vue
Adds a small label/badge to Reactions if isMined is true.
Closes #37
=> Added label to Reaction Card for Mined data
